/* Combine CHD inclusion codes into a single table */

CREATE TABLE SAILWWMCCV.CCU068_CHD_INCLUSION_CODES (
	
	CODE VARCHAR(100),
	CODE_TYPE VARCHAR(100),
	DESCRIPTION VARCHAR(10000),
	PHENOTYPE_ABBREVIATION VARCHAR(100),
	ESC_COMPLEXITY_CLASSIFICATION VARCHAR(10000)
);

CREATE VIEW SAILWWMCCV.CCU068_CHD_INCLUSION_CODES_TEMP AS
	SELECT CODE, 'READ' AS CODE_TYPE, DESCRIPTION, PHENOTYPE_ABBREVIATION, ESC_COMPLEXITY_CLASSIFICATION FROM SAILWWMCCV.READ_INCLUSION_CODES_CCU068 
	UNION ALL
	SELECT CODE, 'ICD10' AS CODE_TYPE, DESCRIPTION, PHENOTYPE_ABBREVIATION, ESC_COMPLEXITY_CLASSIFICATION FROM SAILWWMCCV.ICD10_INCLUSION_CODES_CCU068
	UNION ALL
	SELECT CODE, 'OPCS4' AS CODE_TYPE, DESCRIPTION, PHENOTYPE_ABBREVIATION, ESC_COMPLEXITY_CLASSIFICATION FROM SAILWWMCCV.OPCS4_INCLUSION_CODES_CCU068;
	
INSERT INTO SAILWWMCCV.CCU068_CHD_INCLUSION_CODES 
SELECT * FROM SAILWWMCCV.CCU068_CHD_INCLUSION_CODES_TEMP
WHERE CODE != '';


/* Combine exclusion codes */
CREATE VIEW SAILWWMCCV.CCU068_EXCLUSION_CODES_TEMP AS(

SELECT CODE, 'ICD10' AS CODE_TYPE FROM SAILWWMCCV.ICD10_EXCLUSION_CODES_CCU068
UNION ALL
SELECT CODE, 'OPCS4' AS CODE_TYPE FROM SAILWWMCCV.OPCS4_EXCLUSION_CODES_CCU068
UNION ALL
SELECT CODE, 'READ' AS CODE_TYPE FROM SAILWWMCCV.READ_EXCLUSION_CODES_CCU068
);

CREATE TABLE SAILWWMCCV.CCU068_EXCLUSION_CODES(
	CODE VARCHAR(100),
	CODE_TYPE VARCHAR(10)
);

INSERT INTO SAILWWMCCV.CCU068_EXCLUSION_CODES
SELECT * FROM SAILWWMCCV.CCU068_EXCLUSION_CODES_TEMP;

/* Combine age threshold codes */

CREATE VIEW SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES_TEMP AS(

SELECT CODE, 'ICD10' AS CODE_TYPE FROM SAILWWMCCV.ICD10_AGE_THRESHOLD_CODES_CCU068
UNION ALL
SELECT CODE, 'OPCS4' AS CODE_TYPE FROM SAILWWMCCV.OPCS4_AGE_THRESHOLD_CODES_CCU068
UNION ALL
SELECT CODE, 'READ' AS CODE_TYPE FROM SAILWWMCCV.READ_AGE_THRESHOLD_CODES_CCU068
);

CREATE TABLE SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES(
	CODE VARCHAR(100),
	CODE_TYPE VARCHAR(10)
);

INSERT INTO SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES
SELECT * FROM SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES_TEMP;





/* Find eligible IDs */

CREATE VIEW SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION
AS 
SELECT
    DISTINCT(gp.ALF_E) AS ID
FROM
    C19_COHORT_WLGP_PATIENT_ALF_CLEANSED gp
LEFT JOIN C19_COHORT_ADDE_DEATHS dod ON
    gp.ALF_E = dod.ALF_E
WHERE
    gp.LSOA_CD LIKE 'W%'
    AND ((DATE(dod.DEATH_REG_DT) >= CAST('2020-03-01' AS DATE)) OR dod.ALF_E IS NULL);


/* GP eligible IDs WITH CHD CODE */

CREATE VIEW SAILWWMCCV.CCU068_WLGP_CHD_IDS_PRE_VACCINATION
AS
SELECT DISTINCT ID
FROM (
	SELECT DISTINCT
	    ei.ID,
	    CAST(gp.EVENT_CD AS VARCHAR(100)) AS CODE,
	    CAST('READ' AS VARCHAR(10)) AS CODE_TYPE
	FROM
	    C19_COHORT_WLGP_GP_EVENT_CLEANSED gp
	INNER JOIN SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION ei ON
	    ei.ID = gp.ALF_E
    ) gp
INNER JOIN SAILWWMCCV.READ_INCLUSION_CODES_CCU068 chd_read
ON gp.CODE = chd_read.CODE AND gp.CODE_TYPE = 'READ'
WHERE chd_read.CODE != '';

    
 /* PEDW DIAG eligible IDs WITH CHD CODE */

CREATE VIEW SAILWWMCCV.CCU068_PEDW_DIAG_CHD_IDS_PRE_VACCINATION
AS
SELECT DISTINCT ID
FROM (
	SELECT DISTINCT
	    ei.ID,
	    sp.GNDR_CD AS GENDER,
	    CAST(DIAG_CD_1234 AS VARCHAR(100)) AS CODE,
	    CAST('ICD10' AS VARCHAR(10)) AS CODE_TYPE
	FROM
	    C19_COHORT_PEDW_DIAG diag
	INNER JOIN C19_COHORT_PEDW_SPELL sp ON
	    sp.SPELL_NUM_E = diag.SPELL_NUM_E
	INNER JOIN SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION ei ON
	    ei.ID = sp.ALF_E
	 ) pedw
INNER JOIN SAILWWMCCV.ICD10_INCLUSION_CODES_CCU068 chd_icd
ON pedw.CODE = chd_icd.CODE AND pedw.CODE_TYPE = 'ICD10';


 /* PEDW OPER eligible IDs WITH CHD CODE */

CREATE VIEW SAILWWMCCV.CCU068_PEDW_OPER_CHD_IDS_PRE_VACCINATION
AS
SELECT DISTINCT ID
FROM (
	SELECT DISTINCT
	    ei.ID,
	    CAST(CONCAT(oper.OPER_CD_123,
	    oper.OPER_CD_4) AS VARCHAR(100)) AS CODE,
	    CAST('OPCS4' AS VARCHAR(10)) AS CODE_TYPE
	FROM
	    C19_COHORT_PEDW_OPER oper
	INNER JOIN C19_COHORT_PEDW_SPELL sp ON
	    sp.SPELL_NUM_E = oper.SPELL_NUM_E
	INNER JOIN SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION ei ON
	    ei.ID = sp.ALF_E 
    ) pedw_oper
INNER JOIN SAILWWMCCV.OPCS4_INCLUSION_CODES_CCU068 chd_opcs
ON pedw_oper.CODE = chd_opcs.CODE AND pedw_oper.CODE_TYPE = 'OPCS4';


/* OPDW DIAG eligible IDs with CHD code */

CREATE VIEW SAILWWMCCV.CCU068_OPDW_DIAG_CHD_IDS_PRE_VACCINATION
AS
SELECT DISTINCT ID
FROM (
	SELECT DISTINCT
	    ei.ID,
	    CAST(CONCAT(op.DIAG_CD_123,
	    op.DIAG_CD_4) AS VARCHAR(100)) AS CODE,
	    CAST('ICD10' AS VARCHAR(10)) AS CODE_TYPE
	FROM
	    C19_COHORT_OPDW_OUTPATIENTS_DIAG op
	INNER JOIN C19_COHORT_OPDW_OUTPATIENTS opdw ON
	    opdw.ATT_ID_E = op.ATT_ID_E
	INNER JOIN SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION ei ON
	    ei.ID = opdw.ALF_E
    ) opdw
INNER JOIN SAILWWMCCV.ICD10_INCLUSION_CODES_CCU068 chd_icd
ON opdw.CODE = chd_icd.CODE AND opdw.CODE_TYPE = 'ICD10';

/* OPDW OPER eligible IDs with CHD code */

CREATE VIEW SAILWWMCCV.CCU068_OPDW_OPER_CHD_IDS_PRE_VACCINATION
AS
SELECT DISTINCT ID
FROM (
	SELECT DISTINCT
	    ei.ID,
	    CAST(CONCAT(outpatient_ops.OPER_CD_123,
	    outpatient_ops.OPER_CD_4) AS VARCHAR(100)) AS CODE,
	    CAST('OPCS4' AS VARCHAR(10))  AS CODE_TYPE
	FROM
	    C19_COHORT_OPDW_OUTPATIENTS_OPER outpatient_ops
	INNER JOIN C19_COHORT_OPDW_OUTPATIENTS opdw ON
	    opdw.ATT_ID_E = outpatient_ops.ATT_ID_E
	INNER JOIN SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION ei ON
	    ei.ID = opdw.ALF_E 
    ) opdw_oper
INNER JOIN SAILWWMCCV.OPCS4_INCLUSION_CODES_CCU068 chd_opcs
ON opdw_oper.CODE = chd_opcs.CODE AND opdw_oper.CODE_TYPE = 'OPCS4';


/* Combine CHD IDs from the five tables */


CREATE TABLE SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION (
	ID BIGINT);

CREATE VIEW SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_TEMP_PRE_VACCINATION 
AS
SELECT ID FROM SAILWWMCCV.CCU068_WLGP_CHD_IDS_PRE_VACCINATION
UNION ALL
SELECT ID FROM SAILWWMCCV.CCU068_PEDW_DIAG_CHD_IDS_PRE_VACCINATION
UNION ALL
SELECT ID FROM SAILWWMCCV.CCU068_PEDW_OPER_CHD_IDS_PRE_VACCINATION
UNION ALL
SELECT ID FROM SAILWWMCCV.CCU068_OPDW_DIAG_CHD_IDS_PRE_VACCINATION
UNION ALL
SELECT ID FROM SAILWWMCCV.CCU068_OPDW_OPER_CHD_IDS_PRE_VACCINATION;

INSERT INTO SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION
SELECT ID FROM SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_TEMP_PRE_VACCINATION;


/* Get all records for CHD IDs from each table */
CREATE VIEW SAILWWMCCV.CCU068_PRE_FILTERED_CHD_RECORDS_TEMP_PRE_VACCINATION AS

/* WLGP */
WITH WLGP_CHD_RECORDS AS (
SELECT
    DISTINCT gp.ALF_E AS ID,
    GNDR_CD AS GENDER,
    WOB AS DOB,
    PRAC_CD_E AS GP_PRACTICE,
    CAST('12345' AS VARCHAR(5)) AS ETHNICITY,
    CAST(gp.EVENT_CD AS VARCHAR(100)) AS CODE,
    CAST('READ' AS VARCHAR(10)) AS CODE_TYPE,
    EVENT_DT AS RECORD_DATE,
    YEAR(EVENT_DT) - YEAR(WOB) AS AGE_AT_RECORD
FROM
    C19_COHORT_WLGP_GP_EVENT_CLEANSED gp
INNER JOIN SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION chd_ids ON
    gp.ALF_E = chd_ids.ID),
/* PEDW DIAG */
PEDW_DIAG_CHD_RECORDS AS (
SELECT
    DISTINCT sp.ALF_E AS ID,
    sp.GNDR_CD AS GENDER,
    CAST(CONCAT(CAST(EPI_STR_YR AS INT) - AGE_EPI_STR_YR,
    '-01-01')AS DATE) AS DOB,
    sp.REG_GP_PRAC_CD_E AS GP_PRACTICE,
    CAST(sp.ETH_GRP_DERIVED_CD AS VARCHAR(5))AS ETHNICITY,
    CAST(DIAG_CD_1234 AS VARCHAR(100)) AS CODE,
    CAST('ICD10' AS VARCHAR(10)) AS CODE_TYPE,
    ADMIS_DT AS RECORD_DATE,
    AGE_EPI_STR_YR AS AGE_AT_RECORD
FROM
    C19_COHORT_PEDW_EPISODE diag
INNER JOIN C19_COHORT_PEDW_SPELL sp ON
    sp.SPELL_NUM_E = diag.SPELL_NUM_E
INNER JOIN SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION chd_ids ON
    sp.ALF_E = chd_ids.ID),
/* PEDW OPER */
PEDW_OPER_CHD_RECORDS AS (
SELECT
    DISTINCT sp.ALF_E,
    sp.GNDR_CD AS GENDER,
    CAST(CONCAT(CAST(EPI_STR_YR AS INT) - AGE_EPI_STR_YR,
    '-01-01')AS DATE) AS DOB,
    sp.REG_GP_PRAC_CD_E AS GP_PRACTICE,
    sp.ETH_GRP_DERIVED_CD AS ETHNICITY,
    CAST(CONCAT(oper.OPER_CD_123,
    oper.OPER_CD_4) AS VARCHAR(100)) AS CODE,
    CAST('OPCS4' AS VARCHAR(10)) AS CODE_TYPE,
    ADMIS_DT AS RECORD_DATE,
    AGE_EPI_STR_YR AS AGE_AT_RECORD
FROM
    C19_COHORT_PEDW_EPISODE oper
INNER JOIN C19_COHORT_PEDW_SPELL sp ON
    sp.SPELL_NUM_E = oper.SPELL_NUM_E
INNER JOIN SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION chd_ids ON
    sp.ALF_E = chd_ids.ID),
/* OPDW DIAG */
OPDW_DIAG_CHD_RECORDS AS (
SELECT
    DISTINCT opdw.ALF_E AS ID,
    opdw.GNDR_CD AS GENDER,
    CAST(CONCAT(YEAR(opdw.ATTEND_DT) - opdw.AGE_AT_APPT,
    '-01-01') AS DATE) AS DOB,
    opdw.REG_PRAC_CD_E AS GP_PRACTICE,
    CAST('12345' AS VARCHAR(5)) AS ETHNICITY,
    CAST(op.DIAG_CD_4 AS VARCHAR(100)) AS CODE,
    CAST('ICD10' AS VARCHAR(10)) AS CODE_TYPE,
    opdw.ATTEND_DT AS RECORD_DATE,
    opdw.AGE_AT_APPT AS AGE_AT_RECORD
FROM
    C19_COHORT_OPDW_OUTPATIENTS_DIAG op
INNER JOIN C19_COHORT_OPDW_OUTPATIENTS opdw ON
    opdw.ATT_ID_E = op.ATT_ID_E
INNER JOIN SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION chd_ids ON
    opdw.ALF_E = chd_ids.ID),
/* OPDW OPER */
OPDW_OPER_CHD_RECORDS AS (
SELECT
    DISTINCT opdw.ALF_E AS ID,
    opdw.GNDR_CD AS GENDER,
    CAST(CONCAT(YEAR(opdw.ATTEND_DT) - opdw.AGE_AT_APPT,
    '-01-01') AS DATE) AS DOB,
    opdw.REG_PRAC_CD_E AS GP_PRACTICE,
    CAST('12345' AS VARCHAR(5)) AS ETHNICITY,
    CAST(CONCAT(outpatient_ops.OPER_CD_123,
    outpatient_ops.OPER_CD_4) AS VARCHAR(100)) AS CODE,
    CAST('OPCS4' AS VARCHAR(10)) AS CODE_TYPE,
    opdw.ATTEND_DT AS RECORD_DATE,
    opdw.AGE_AT_APPT AS AGE_AT_RECORD
FROM
    C19_COHORT_OPDW_OUTPATIENTS_OPER outpatient_ops
INNER JOIN C19_COHORT_OPDW_OUTPATIENTS opdw ON
    opdw.ATT_ID_E = outpatient_ops.ATT_ID_E
INNER JOIN SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION chd_ids ON
    opdw.ALF_E = chd_ids.ID)
SELECT
    ID, GENDER, DOB, GP_PRACTICE, ETHNICITY, CODE, CODE_TYPE, RECORD_DATE, AGE_AT_RECORD
FROM
	(SELECT * FROM 
	    WLGP_CHD_RECORDS
	UNION ALL
	SELECT
	    *
	FROM
	    PEDW_DIAG_CHD_RECORDS
	UNION ALL
	SELECT
	    *
	FROM
	    PEDW_OPER_CHD_RECORDS
	UNION ALL
	SELECT
	    *
	FROM
	    OPDW_DIAG_CHD_RECORDS
	UNION ALL
	SELECT
	    *
	FROM
	    OPDW_OPER_CHD_RECORDS) records;


/* APPLY FURTHER FILTERING STEPS TO PRE-FILTERED CHD CASES */

/*Find congenital records */
/* Find AV records */
/* Filter out excluded AV records */
/* Combine congenital records and filtered AV records */

CREATE VIEW SAILWWMCCV.CCU068_CASE_CHD_RECORDS_UNMATCHED_PRE_VACCINATION_TEMP AS
WITH CONGENITAL_RECORDS AS
(
SELECT rec.ID, rec.GENDER, rec.DOB,  rec.GP_PRACTICE, rec.ETHNICITY, rec.CODE, rec.CODE_TYPE, rec.RECORD_DATE 
FROM SAILWWMCCV.CCU068_PRE_FILTERED_CHD_RECORDS_TEMP_PRE_VACCINATION rec
INNER JOIN SAILWWMCCV.CCU068_CHD_INCLUSION_CODES inc
ON rec.CODE = inc.CODE AND rec.CODE_TYPE = inc.CODE_TYPE
LEFT JOIN SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES age
ON rec.CODE = age.CODE AND rec.CODE_TYPE = age.CODE_TYPE 
WHERE age.CODE IS NULL
),

AV_RECORDS AS
(
SELECT  rec.ID, rec.GENDER, rec.DOB, rec.GP_PRACTICE, rec.ETHNICITY, rec.CODE, rec.CODE_TYPE, rec.RECORD_DATE, rec.AGE_AT_RECORD
FROM SAILWWMCCV.CCU068_PRE_FILTERED_CHD_RECORDS_TEMP_PRE_VACCINATION rec
INNER JOIN SAILWWMCCV.CCU068_AGE_THRESHOLD_CODES age
ON rec.CODE = age.CODE AND rec.CODE_TYPE = age.CODE_TYPE 
),

AV_DIAGNOSIS_DATES AS
(
SELECT
    ID,
    DOB,
    MIN(RECORD_DATE) AS EARLIEST_DIAGNOSIS,
    MIN(AGE_AT_RECORD) AS AGE_AT_EARLIEST_DIAGNOSIS
FROM
    AV_RECORDS
GROUP BY
    ID,
    DOB
),

EXCLUSION_DIAGNOSIS_DATES AS
(
SELECT
    rec.ID,
    MIN(rec.RECORD_DATE) AS EARLIEST_EXCLUSION_DIAGNOSIS
FROM
    SAILWWMCCV.CCU068_PRE_FILTERED_CHD_RECORDS_TEMP_PRE_VACCINATION rec
INNER JOIN SAILWWMCCV.CCU068_EXCLUSION_CODES exc ON
    exc.CODE = rec.CODE
    AND exc.CODE_TYPE = rec.CODE_TYPE
INNER JOIN
	(SELECT ID FROM AV_RECORDS) av_ids
ON av_ids.ID = rec.ID
GROUP BY
    rec.ID
)
SELECT rec.ID, rec.GENDER, rec.DOB, rec.GP_PRACTICE, rec.ETHNICITY, rec.CODE, rec.CODE_TYPE, rec.RECORD_DATE
FROM AV_RECORDS rec
INNER JOIN AV_DIAGNOSIS_DATES av_date
ON av_date.ID = rec.ID
left JOIN EXCLUSION_DIAGNOSIS_DATES exc_date
ON exc_date.ID = rec.ID
WHERE AGE_AT_EARLIEST_DIAGNOSIS < 65 
AND ((exc_date.EARLIEST_EXCLUSION_DIAGNOSIS > av_date.EARLIEST_DIAGNOSIS)
OR exc_date.ID IS NULL)
UNION ALL 
SELECT ID, GENDER, DOB, GP_PRACTICE, ETHNICITY, CODE, CODE_TYPE, RECORD_DATE
FROM CONGENITAL_RECORDS;



/* Create empty table to store combined CHD records */
CREATE TABLE SAILWWMCCV.CCU068_CASE_CHD_RECORDS_UNMATCHED_PRE_VACCINATION (

	ID BIGINT,
	GENDER CHARACTER(1),
	DOB DATE,
	GP_PRACTICE BIGINT,
	ETHNICITY VARCHAR(5),
	CODE VARCHAR(100),
	CODE_TYPE VARCHAR(10),
	RECORD_DATE DATE
	);
    
INSERT INTO SAILWWMCCV.CCU068_CASE_CHD_RECORDS_UNMATCHED_PRE_VACCINATION
SELECT * FROM SAILWWMCCV.CCU068_CASE_CHD_RECORDS_UNMATCHED_PRE_VACCINATION_TEMP;


/* Find IDs for potential controls */

CREATE VIEW SAILWWMCCV.CCU068_CONTROL_IDS_UNMATCHED_PRE_VACCINATION_TEMP AS 
WITH CHD_IDS AS (
SELECT
    ID
FROM
    SAILWWMCCV.CCU068_PRE_FILTERED_CHD_IDS_PRE_VACCINATION)
SELECT
    el.ID
FROM
    SAILWWMCCV.ELIGIBLE_IDS_PRE_VACCINATION el
LEFT JOIN CHD_IDS chd ON
    el.ID = chd.ID
WHERE
    CHD.ID IS NULL;
    
CREATE TABLE SAILWWMCCV.CCU068_CONTROL_IDS_UNMATCHED_PRE_VACCINATION (
		ID BIGINT);
	
INSERT INTO SAILWWMCCV.CCU068_CONTROL_IDS_UNMATCHED_PRE_VACCINATION
SELECT ID FROM SAILWWMCCV.CCU068_CONTROL_IDS_UNMATCHED_PRE_VACCINATION_TEMP;

