/* Find people who had their FIRST covid infection during WINDOW */

CREATE VIEW SAILWWMCCV.CCU068_CHD_RECORDS_COVID_INFECTIONS_POST_VACCINATION AS

SELECT ID, INFECTION_DATE
FROM
(
	SELECT records.ID, INFECTION_DATE, 
	ROW_NUMBER() OVER(PARTITION BY records.ID
					  ORDER BY infections.INFECTION_DATE) AS ROW
	FROM (
		SELECT DISTINCT ID
		FROM SAILWWMCCV.CCU068_CASE_CHD_RECORDS_UNMATCHED_POST_VACCINATION
		) records
	INNER JOIN 
		(
		SELECT ALF_E AS ID, SPCM_COLLECTED_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_PATD_DF_COVID_LIMS_TESTRESULTS
		WHERE  RESULT_CD IN ( 'D7', 'D6', 'D1', 'LL7')
		UNION ALL
		SELECT ALF_E AS ID, EVENT_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_WLGP_GP_EVENT_CLEANSED
		WHERE EVENT_CD IN ('Y20fa', 'Y20fb', 'Y211c', 'Y228e', 'A7951', '4J3R1')
		UNION ALL
		SELECT sp.ALF_E AS ID, EPI_STR_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_PEDW_EPISODE epi
		INNER JOIN SAILWWMCCV.WMCC_PEDW_SPELL sp
		ON epi.SPELL_NUM_E = sp.SPELL_NUM_E
		WHERE epi.DIAG_CD_1234 IN ('U071', 'U072')
		) infections
	ON records.ID = infections.ID
)
WHERE (INFECTION_DATE BETWEEN CAST('2021-03-01' AS DATE) AND CAST('2022-04-01' AS DATE))
AND ROW = 1;

SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CHD_RECORDS_COVID_INFECTIONS_POST_VACCINATION;

/* Add vaccination records, exclude people unvaccinated WHEN FIRST caught COVID */

CREATE VIEW SAILWWMCCV.CCU068_CHD_CASE_VACCINATIONS AS 

WITH VACCINATIONS AS (
SELECT ALF_E AS ID, VACC_DATE_OF_VACCINE AS VACCINATION_DATE, ROW_NUMBER() 
OVER (PARTITION BY ALF_E ORDER BY VACC_DATE_OF_VACCINE) AS ROW_ASC, ROW_NUMBER() 
OVER (PARTITION BY ALF_E ORDER BY VACC_DATE_OF_VACCINE DESC) AS ROW_DESC
FROM 
SAILWMCCV.C19_COHORT_CVVD_DF_WIS_OUTCOMEDATAV2 vacc
WHERE VACC_DATE_OF_VACCINE > CAST('2020-12-08' AS DATE)),

FIRST_VACCINATIONS AS (

SELECT inf.ID, vacc.VACCINATION_DATE, inf.INFECTION_DATE FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CHD_RECORDS_COVID_INFECTIONS_POST_VACCINATION inf
ON vacc.ID = inf.ID
WHERE ROW_ASC = 1 AND VACCINATION_DATE + 14 < INFECTION_DATE),

SECOND_VACCINATIONS AS (
SELECT inf.ID, vacc.VACCINATION_DATE FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CHD_RECORDS_COVID_INFECTIONS_POST_VACCINATION inf
ON vacc.ID = inf.ID
WHERE ROW_ASC = 2 
), 

MOST_RECENT_VACCINATIONS AS (
SELECT inf.ID, vacc.VACCINATION_DATE, ROW_NUMBER() OVER (PARTITION BY vacc.ID ORDER BY vacc.VACCINATION_DATE DESC) 
AS vacc_row
FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CHD_RECORDS_COVID_INFECTIONS_POST_VACCINATION inf
ON vacc.ID = inf.ID
WHERE vacc.VACCINATION_DATE < inf.INFECTION_DATE
)


SELECT inf.ID, inf.VACCINATION_DATE AS FIRST_VACCINATION_DATE,  second_vacc.VACCINATION_DATE AS SECOND_VACCINATION_DATE, 
inf.INFECTION_DATE, recent_vacc.VACCINATION_DATE AS most_recent_vaccination_date,
(CASE WHEN second_vacc.VACCINATION_DATE + 14 > INFECTION_DATE THEN 'Partial' ELSE 'Full' END) AS VACCINATED_PRE_INFECTION
FROM 
FIRST_VACCINATIONS inf
LEFT JOIN 
SECOND_VACCINATIONS second_vacc
ON second_vacc.ID = inf.ID
LEFT JOIN 
MOST_RECENT_VACCINATIONS recent_vacc
ON recent_vacc.ID = inf.ID
WHERE VACC_ROW = 1;

SELECT DISTINCT(COUNT(ID)) 
FROM SAILWWMCCV.CCU068_CHD_CASE_VACCINATIONS_POST_VACCINATION;

/* Add hospitalisation records from PEDW - U071/U072*/

CREATE VIEW SAILWWMCCV.CCU068_CHD_CASE_HOSPITALISATIONS_POST_VACCINATION AS

WITH HOSPITALISATIONS AS(
	SELECT sp.ALF_E AS ID, EPI_STR_DT AS HOSPITALISATION_DATE, ROW_NUMBER() OVER (PARTITION BY ALF_E ORDER BY EPI_STR_DT) AS ROW
			FROM
			SAILWWMCCV.WMCC_PEDW_EPISODE epi
			INNER JOIN SAILWWMCCV.WMCC_PEDW_SPELL sp
			ON epi.SPELL_NUM_E = sp.SPELL_NUM_E
			WHERE epi.DIAG_CD_1234 IN ('U071', 'U072')
),
FIRST_HOSPITALISATIONS AS (
	SELECT chd_case.ID, HOSPITALISATION_DATE
	FROM 
	HOSPITALISATIONS hosp
	INNER JOIN SAILWWMCCV.CCU068_CHD_CASE_INFECTIONS chd_case
	ON hosp.ID = chd_case.ID 
	WHERE
	ROW = 1 AND HOSPITALISATION_DATE <= INFECTION_DATE + 20 AND HOSPITALISATION_DATE >= INFECTION_DATE)
	
SELECT  chd_cases.ID, INFECTION_DATE, FIRST_VACCINATION_DATE, SECOND_VACCINATION_DATE, HOSPITALISATION_DATE, 
(CASE
WHEN HOSPITALISATION_DATE IS NULL THEN 'No'
ELSE 'Yes'
END) AS HOSPITALISED_WITH_FIRST_INFECTION, MOST_RECENT_VACCINATION_DATE, VACCINATED_PRE_INFECTION
FROM
SAILWWMCCV.CCU068_CHD_CASE_VACCINATIONS chd_cases
LEFT JOIN FIRST_HOSPITALISATIONS hosps
ON hosps.ID = chd_cases.ID;

SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CHD_CASE_HOSPITALISATIONS_POST_VACCINATION WHERE HOSPITALISED_WITH_FIRST_INFECTION = 'Yes';


/* Add death records - ADDE /CDDS*/

CREATE VIEW SAILWWMCCV.CCU068_CHD_CASE_DEATHS_POST_VACCINATION AS

WITH DEATHS AS (
	SELECT death.ID, death.DATE_OF_DEATH, 
	ROW_NUMBER() OVER (PARTITION BY death.ID ORDER BY death.DATE_OF_DEATH) AS ROW
	FROM
	(SELECT ALF_E AS ID, DEATH_DT AS DATE_OF_DEATH
	FROM 
	SAILWMCCV.C19_COHORT_ADDE_DEATHS
	WHERE DEATHCAUSE_DIAG_UNDERLYING_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_1_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_2_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_3_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_4_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_5_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_6_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_7_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_8_CD IN ('U071', 'U072')
	UNION ALL
	SELECT ALF_E AS ID, DEATH_REGISTRATION_DT AS DATE_OF_DEATH 
	FROM 
	SAILWMCCV.C19_COHORT_CDDS_DF_COVID_DEATHS_CONSOLIDATED
	WHERE ALL_CAUSES LIKE ('%U07%')) death),
	
	
FIRST_DEATHS AS (
	SELECT chd_case.ID, DATE_OF_DEATH
	FROM 
	DEATHS death
	INNER JOIN SAILWWMCCV.CCU068_CHD_CASE_HOSPITALISATIONS_POST_VACCINATION chd_case
	ON death.ID = chd_case.ID 
	WHERE
	ROW = 1 AND DATE_OF_DEATH <= INFECTION_DATE + 28 AND DATE_OF_DEATH >= INFECTION_DATE)

SELECT chd_cases.ID, INFECTION_DATE, FIRST_VACCINATION_DATE, SECOND_VACCINATION_DATE, HOSPITALISATION_DATE,
HOSPITALISED_WITH_FIRST_INFECTION, DATE_OF_DEATH, (CASE WHEN DATE_OF_DEATH IS NULL THEN 'No' ELSE 'Yes' END)
AS DEATH_FROM_FIRST_INFECTION, MOST_RECENT_VACCINATION_DATE, VACCINATED_PRE_INFECTION
FROM
SAILWWMCCV.CCU068_CHD_CASE_HOSPITALISATIONS_POST_VACCINATION chd_cases
LEFT JOIN 
FIRST_DEATHS death
ON death.ID = chd_cases.ID;


SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CHD_CASE_DEATHS WHERE DATE_OF_DEATH IS NOT NULL;

/*** SAME FOR CONTROLS ***/

/* Find people who had their FIRST covid infection during WINDOW */

CREATE VIEW SAILWWMCCV.CCU068_CONTROL_RECORDS_COVID_INFECTIONS_PRE_VACCINATION AS

SELECT ID, INFECTION_DATE
FROM
(
	SELECT records.ID, INFECTION_DATE, 
	ROW_NUMBER() OVER(PARTITION BY records.ID
					  ORDER BY infections.INFECTION_DATE) AS ROW
	FROM (
		SELECT DISTINCT ID
		FROM SAILWWMCCV.CCU068_CONTROL_IDS_UNMATCHED_POST_VACCINATION
		) records
	INNER JOIN 
		(
		SELECT ALF_E AS ID, SPCM_COLLECTED_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_PATD_DF_COVID_LIMS_TESTRESULTS
		WHERE RESULT_CD IN ( 'D7', 'D6', 'D1', 'LL7')
		UNION ALL
		SELECT ALF_E AS ID, EVENT_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_WLGP_GP_EVENT_CLEANSED
		WHERE EVENT_CD IN ('Y20fa', 'Y20fb', 'Y211c', 'Y228e', 'A7951', '4J3R1')
		UNION ALL
		SELECT sp.ALF_E AS ID, EPI_STR_DT AS INFECTION_DATE 
		FROM
		SAILWWMCCV.WMCC_PEDW_EPISODE epi
		INNER JOIN SAILWWMCCV.WMCC_PEDW_SPELL sp
		ON epi.SPELL_NUM_E = sp.SPELL_NUM_E
		WHERE epi.DIAG_CD_1234 IN ('U071', 'U072')
		) infections
	ON records.ID = infections.ID
)
WHERE (INFECTION_DATE BETWEEN CAST('2021-03-01' AS DATE) AND CAST('2022-04-01' AS DATE))
AND ROW = 1;

SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CONTROL_RECORDS_COVID_INFECTIONS;

/* Add vaccination records, exclude people unvaccinated WHEN FIRST caught COVID */

CREATE VIEW SAILWWMCCV.CCU068_CHD_CONTROL_VACCINATIONS_PRE_VACCINATION AS 

WITH VACCINATIONS AS (
SELECT ALF_E AS ID, VACC_DATE_OF_VACCINE AS VACCINATION_DATE, ROW_NUMBER() 
OVER (PARTITION BY ALF_E ORDER BY VACC_DATE_OF_VACCINE) AS ROW_ASC,
ROW_NUMBER() OVER (PARTITION BY ALF_E ORDER BY VACC_DATE_OF_VACCINE DESC) AS ROW_DESC
FROM 
SAILWMCCV.C19_COHORT_CVVD_DF_WIS_OUTCOMEDATAV2 vacc
WHERE VACC_DATE_OF_VACCINE > CAST('2020-12-08' AS DATE)),

FIRST_VACCINATIONS AS (

SELECT inf.ID, vacc.VACCINATION_DATE, inf.INFECTION_DATE FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CONTROL_RECORDS_COVID_INFECTIONS inf
ON vacc.ID = inf.ID
WHERE ROW_ASC = 1 AND VACCINATION_DATE +14 < INFECTION_DATE),

SECOND_VACCINATIONS AS (
SELECT inf.ID, vacc.VACCINATION_DATE FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CONTROL_RECORDS_COVID_INFECTIONS inf
ON vacc.ID = inf.ID
WHERE ROW_ASC = 2 
), 

MOST_RECENT_VACCINATIONS AS (
SELECT inf.ID, vacc.VACCINATION_DATE, ROW_NUMBER() OVER (PARTITION BY vacc.ID ORDER BY vacc.VACCINATION_DATE DESC) AS VACC_ROW
FROM VACCINATIONS vacc
INNER JOIN 
SAILWWMCCV.CCU068_CONTROL_RECORDS_COVID_INFECTIONS inf
ON vacc.ID = inf.ID
WHERE vacc.VACCINATION_DATE < inf.INFECTION_DATE 
)


SELECT inf.ID, inf.VACCINATION_DATE AS FIRST_VACCINATION_DATE,  second_vacc.VACCINATION_DATE AS SECOND_VACCINATION_DATE, 
inf.INFECTION_DATE, recent_vacc.VACCINATION_DATE AS MOST_RECENT_VACCINATION_DATE,
(CASE WHEN second_vacc.VACCINATION_DATE + 14 > INFECTION_DATE THEN 'Partial' ELSE 'Full' END) AS VACCINATED_PRE_INFECTION
FROM 
FIRST_VACCINATIONS inf
LEFT JOIN 
SECOND_VACCINATIONS second_vacc
ON second_vacc.ID = inf.ID
LEFT JOIN MOST_RECENT_VACCINATIONS recent_vacc
ON recent_vacc.ID = inf.ID
WHERE vacc_row = 1;

SELECT DISTINCT(COUNT(ID)) 
FROM SAILWWMCCV.CCU068_CHD_CONTROL_VACCINATIONS;

/* Add hospitalisation records from PEDW - U071/U072*/

CREATE VIEW SAILWWMCCV.CCU068_CHD_CONTROL_HOSPITALISATIONS_PRE_VACCINATION AS

WITH HOSPITALISATIONS AS(
	SELECT sp.ALF_E AS ID, EPI_STR_DT AS HOSPITALISATION_DATE, ROW_NUMBER() OVER (PARTITION BY ALF_E ORDER BY EPI_STR_DT) AS ROW
			FROM
			SAILWWMCCV.WMCC_PEDW_EPISODE epi
			INNER JOIN SAILWWMCCV.WMCC_PEDW_SPELL sp
			ON epi.SPELL_NUM_E = sp.SPELL_NUM_E
			WHERE epi.DIAG_CD_1234 IN ('U071', 'U072')
),
FIRST_HOSPITALISATIONS AS (
	SELECT chd_case.ID, HOSPITALISATION_DATE
	FROM 
	HOSPITALISATIONS hosp
	INNER JOIN SAILWWMCCV.CCU068_CHD_CONTROL_VACCINATIONS chd_case
	ON hosp.ID = chd_case.ID 
	WHERE
	ROW = 1 AND HOSPITALISATION_DATE <= INFECTION_DATE + 20 AND HOSPITALISATION_DATE >= INFECTION_DATE)
	
SELECT  chd_cases.ID, INFECTION_DATE, FIRST_VACCINATION_DATE, SECOND_VACCINATION_DATE, HOSPITALISATION_DATE, 
(CASE
WHEN HOSPITALISATION_DATE IS NULL THEN 'No'
ELSE 'Yes'
END) AS HOSPITALISED_WITH_FIRST_INFECTION, MOST_RECENT_VACCINATION_DATE, VACCINATED_PRE_INFECTION
FROM
SAILWWMCCV.CCU068_CHD_CONTROL_VACCINATIONS chd_cases
LEFT JOIN FIRST_HOSPITALISATIONS hosps
ON hosps.ID = chd_cases.ID;

SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CHD_CONTROL_HOSPITALISATIONS WHERE HOSPITALISED_WITH_FIRST_INFECTION = 'Yes';


/* Add death records - ADDE /CDDS*/

CREATE VIEW SAILWWMCCV.CCU068_CHD_CONTROL_DEATHS_PRE_VACCINATION AS

WITH DEATHS AS (
	SELECT death.ID, death.DATE_OF_DEATH, 
	ROW_NUMBER() OVER (PARTITION BY death.ID ORDER BY death.DATE_OF_DEATH) AS ROW
	FROM
	(SELECT ALF_E AS ID, DEATH_DT AS DATE_OF_DEATH
	FROM 
	SAILWMCCV.C19_COHORT_ADDE_DEATHS
	WHERE DEATHCAUSE_DIAG_UNDERLYING_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_1_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_2_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_3_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_4_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_5_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_6_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_7_CD IN ('U071', 'U072')
	OR DEATHCAUSE_DIAG_8_CD IN ('U071', 'U072')
	UNION ALL
	SELECT ALF_E AS ID, DEATH_REGISTRATION_DT AS DATE_OF_DEATH 
	FROM 
	SAILWMCCV.C19_COHORT_CDDS_DF_COVID_DEATHS_CONSOLIDATED
	WHERE ALL_CAUSES LIKE ('%U07%')) death),
	
FIRST_DEATHS AS (
	SELECT chd_case.ID, DATE_OF_DEATH
	FROM 
	DEATHS death
	INNER JOIN SAILWWMCCV.CCU068_CHD_CONTROL_HOSPITALISATIONS chd_case
	ON death.ID = chd_case.ID 
	WHERE
	ROW = 1 AND DATE_OF_DEATH <= INFECTION_DATE + 28 AND DATE_OF_DEATH >= INFECTION_DATE)

SELECT chd_cases.ID, INFECTION_DATE, FIRST_VACCINATION_DATE, SECOND_VACCINATION_DATE, HOSPITALISATION_DATE,
HOSPITALISED_WITH_FIRST_INFECTION, DATE_OF_DEATH, (CASE WHEN DATE_OF_DEATH IS NULL THEN 'No' ELSE 'Yes' END)
AS DEATH_FROM_FIRST_INFECTION, MOST_RECENT_VACCINATION_DATE, VACCINATED_PRE_INFECTION
FROM
SAILWWMCCV.CCU068_CHD_CONTROL_HOSPITALISATIONS chd_cases
LEFT JOIN 
FIRST_DEATHS death
ON death.ID = chd_cases.ID;


SELECT COUNT(DISTINCT(ID)) FROM SAILWWMCCV.CCU068_CHD_CONTROL_DEATHS_PRE_VACCINATION WHERE DATE_OF_DEATH IS NOT NULL;


/* Create tables of covid outcomes */

CREATE TABLE SAILWWMCCV.CCU068_CHD_CASE_COVID_PRE_VACCINATION (
ID BIGINT,
INFECTION_DATE DATE,
FIRST_VACCINATION_DATE DATE,
SECOND_VACCINATION_DATE DATE,
HOSPITALISATION_DATE DATE,
HOSPITALISED_WITH_FIRST_COVID_INFECTION VARCHAR(4),
DATE_OF_DEATH DATE,
DEATH_FROM_FIRST_INFECTION VARCHAR(4),
MOST_RECENT_VACCINATION_DATE DATE,
VACCINATED_PRE_INFECTION VARCHAR(10)
);


INSERT INTO SAILWWMCCV.CCU068_CHD_CASE_COVID
SELECT * FROM SAILWWMCCV.CCU068_CHD_CASE_DEATHS;


CREATE TABLE SAILWWMCCV.CCU068_CHD_CONTROLS_COVID (
ID BIGINT,
INFECTION_DATE DATE,
FIRST_VACCINATION_DATE DATE,
SECOND_VACCINATION_DATE DATE,
HOSPITALISATION_DATE DATE,
HOSPITALISED_WITH_FIRST_COVID_INFECTION VARCHAR(4),
DATE_OF_DEATH DATE,
DEATH_FROM_FIRST_INFECTION VARCHAR(4),
MOST_RECENT_VACCINATION_DATE DATE,
VACCINATED_PRE_INFECTION VARCHAR(10)
);


INSERT INTO SAILWWMCCV.CCU068_CHD_CONTROLS_COVID
SELECT * FROM SAILWWMCCV.CCU068_CHD_CONTROL_DEATHS
